--DROP TABLE if EXISTS statistic CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255),
    email VARCHAR(255)
    );