DROP TABLE if EXISTS statistic CASCADE;
DROP TABLE if EXISTS categories CASCADE;
DROP TABLE if EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255),
    email VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR,
    category_id INTEGER REFERENCES categories,
    user_id INTEGER REFERENCES users,
    description VARCHAR,
    event_date TIMESTAMP,
    location_latitude DOUBLE PRECISION,
    location_longitude DOUBLE PRECISION,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR,
    created_on TIMESTAMP,
    published_on TIMESTAMP,
    title VARCHAR
)