services:
  stats-server:
    build: ./stats-service/stat-server
    image: statistic-image
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SERVER_PORT=9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

  ewm-service:
    build: ./main-service
    image: main-image
    container_name: ewm-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:16.1
    container_name: main-db-container
    ports:
      - "8087:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
