services:
  stats-server:
    build: ./stats-service/stat-server
    image: statistic-image
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
