CREATE TABLE IF NOT EXISTS statistic (
                                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         app VARCHAR(255),
    uri VARCHAR(255),
    ip VARCHAR(50),
    timestamp TIMESTAMP NOT NULL
    );